In [29]:
import numpy as np
import pandas as pd

In [30]:
df = pd.read_csv('customer.csv')

In [31]:
df.sample(5)

age  gender   review education purchased
10   98  Female     Good        UG       Yes
31   22  Female     Poor    School       Yes
12   51    Male     Poor    School        No
15   75    Male     Poor        UG        No
32   92    Male  Average        UG       Yes

In [32]:
df = df.iloc[:,2:]


In [33]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# Ordinal Encoding

Encode categorical features as an integer array.

The input to this transformer should be an array-like of integers or strings, denoting the values taken on by categorical (discrete) features. The features are converted to ordinal integers. This results in a single column of integers (0 to n_categories - 1) per feature.

In [34]:
from sklearn.preprocessing import OrdinalEncoder

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1],test_size=0.2)

In [36]:
X_train


review education
42     Good        PG
1      Poor        UG
18     Good    School
33     Good        PG
20  Average    School
9      Good        UG
23     Good    School
14     Poor        PG
10     Good        UG
24  Average        PG
22     Poor        PG
47     Good        PG
32  Average        UG
48     Good        UG
4   Average        UG
44  Average        UG
2      Good        PG
8   Average        UG
11     Good        UG
35     Poor    School
0   Average    School
27     Poor        PG
12     Poor    School
25     Good    School
43     Poor        PG
30  Average        UG
7      Poor    School
37  Average        PG
5   Average    School
40     Good    School
13  Average    School
31     Poor    School
6      Good    School
45     Poor        PG
41     Good        PG
3      Good        PG
15     Poor        UG
28     Poor    School
21  Average        PG
46     Poor        PG

In [37]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [38]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [39]:
X_train = oe.transform(X_train)

In [40]:
X_train

array([[2., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [0., 2.]])

In [41]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [42]:
X_train

array([[2., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [0., 2.]])

# Label Encoding 

Encode target labels with value between 0 and n_classes-1.

This transformer should be used to encode target values, i.e. y, and not the input X.

In [43]:
from sklearn.preprocessing import LabelEncoder

In [22]:
le = LabelEncoder()

In [27]:
le.fit(y_train)

LabelEncoder()

In [24]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [25]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [26]:
y_train

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1])